# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  release:
    types: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "package.json, LICENSE, README.md"

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('File does not match branch name')
